import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import "./globals.scss";

const inter = Inter({ subsets: ['latin', 'cyrillic'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: "ISS Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
